[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.8.2", features = ["csr", "nightly"] }
leptos_router = "0.8.2"
orgize = "0.9.0"
reqwest = "0.12.20"
